// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSTT():Promise<number>;

export function ProcessFiles(arg1:Array<string>,arg2:number):Promise<void>;

export function ScanOrderFolder():Promise<Array<string>>;

export function SelectFiles():Promise<Array<string>>;

export function SetSTT(arg1:number):Promise<void>;
