// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appsettings} from '../models';
import {main} from '../models';

export function ConfirmPrice(arg1:number,arg2:number):Promise<void>;

export function GetAppSettings():Promise<appsettings.Settings>;

export function GetSTT():Promise<number>;

export function ProcessFiles(arg1:Array<string>,arg2:number):Promise<void>;

export function SaveAppSettings(arg1:appsettings.Settings):Promise<void>;

export function ScanOrderFolder():Promise<Array<string>>;

export function SelectFiles():Promise<Array<string>>;

export function SendZaloMessages(arg1:Array<main.ZaloJob>):Promise<void>;

export function SetSTT(arg1:number):Promise<void>;

export function UpdateJITPeriod(arg1:Array<number>,arg2:string,arg3:string,arg4:string):Promise<void>;
