// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTMDTMissing() {
  return window['go']['main']['App']['CancelTMDTMissing']();
}

export function CancelZaloLogin() {
  return window['go']['main']['App']['CancelZaloLogin']();
}

export function ConfirmPrice(arg1, arg2) {
  return window['go']['main']['App']['ConfirmPrice'](arg1, arg2);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function InitializeApp() {
  return window['go']['main']['App']['InitializeApp']();
}

export function InspectTMDTFiles(arg1) {
  return window['go']['main']['App']['InspectTMDTFiles'](arg1);
}

export function MisaResolveRoutes(arg1) {
  return window['go']['main']['App']['MisaResolveRoutes'](arg1);
}

export function MisaRouteOptions() {
  return window['go']['main']['App']['MisaRouteOptions']();
}

export function ProcessFiles(arg1, arg2) {
  return window['go']['main']['App']['ProcessFiles'](arg1, arg2);
}

export function PushMisa(arg1, arg2) {
  return window['go']['main']['App']['PushMisa'](arg1, arg2);
}

export function RefreshZaloQR() {
  return window['go']['main']['App']['RefreshZaloQR']();
}

export function ResolveTMDTMissing(arg1) {
  return window['go']['main']['App']['ResolveTMDTMissing'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function ScanOrderFolder() {
  return window['go']['main']['App']['ScanOrderFolder']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SendZaloMessages(arg1) {
  return window['go']['main']['App']['SendZaloMessages'](arg1);
}

export function UpdateJITPeriod(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateJITPeriod'](arg1, arg2, arg3, arg4);
}
