// Package maxidi parses Maxidi Việt Nam delivery notes ("Phiếu giao
// hàng", generated by Crystal Reports).
//
// Unlike every other vendor package here, this one has NO counterpart in
// xulydonhang.py — Maxidi was never implemented in the old Python app,
// so nothing below mirrors a Python original and there are no "known
// divergences" to reconcile. The shapes it parses were derived directly
// from the four real archived delivery notes available when it was
// written (two per branch, two order dates), via this repo's own
// extractPageTexts.
//
// Two properties of that extracted text drive every decision here:
//
//  1. Line breaks are NOT reliable. Two of the four samples put the
//     product row's three numbers on three separate lines; the other two
//     fuse the entire row onto one line with no newline anywhere in it —
//     same template, same generator, same page layout. Nothing below may
//     depend on a line offset, so every field is anchored on the
//     template's own printed labels and on the shape of the value.
//
//  2. Labels and values run together with no separator. The page's
//     column headers, its field labels and its data all concatenate
//     ("...(Tiêu chuẩn ngoại quan)8935355302344280085 900.00Thung"), so
//     an anchor has to be a literal label followed immediately by the
//     value, never "the text after a newline".
package maxidi

import (
	"regexp"
	"strings"
)

// taxCodePattern reads the issuing branch's tax code out of the
// letterhead ("...P. Tân Đông HiệpTax Code: 0317899481-002Delivery
// note"). Anchored on the "Delivery note" title that always follows it,
// because the value itself runs straight into that title with no
// separator, so a whitespace-terminated match would swallow it.
var taxCodePattern = regexp.MustCompile(`Tax Code\s*:\s*(.+?)Delivery note`)

// entryDateAndPOPattern reads the order date and the PO number, which
// the template prints in that order directly under the
// "(Số đơn hàng)" label. The PO is captured as "everything up to the
// next column header" rather than by a fixed "HO-PO" prefix: the prefix
// is a Maxidi purchasing-system convention, not something this project
// controls, and anchoring on the template's own printed header is
// stable if that convention ever changes.
var entryDateAndPOPattern = regexp.MustCompile(`(?s)\(Số đơn hàng\)\s*:\s*(\d{1,2}/\d{1,2}/\d{4})\s*(.+?)Barcode`)

// shipDateAndAddressPattern reads the delivery date and the delivery
// address, printed in that order under the "(Nơi giao hàng)" label and
// terminated by the next column header ("Quantity per Unit", which the
// extracted text renders as "Quantityper Unit" — the two words are two
// separate text runs on the page, so the space between them is a layout
// artifact rather than a real character, and \s* covers both shapes).
var shipDateAndAddressPattern = regexp.MustCompile(`(?s)\(Nơi giao hàng\)\s*:\s*(\d{1,2}/\d{1,2}/\d{4})\s*(.+?)Quantity\s*per Unit`)

// remarksPattern reads the free-text note the template prints at the
// bottom of the page, between the signature block and the "Remarks:"
// caption. Note the caption comes AFTER its own value in the extracted
// text: it sits to the left of the note on the page, but later in the
// content stream.
var remarksPattern = regexp.MustCompile(`(?s)Approved by\s*:\s*(.*?)Remarks\s*:`)

// remarksLeadingTotalPattern strips the quantity column's own page total
// (e.g. " 900.00"), which the generator emits immediately before the
// remarks text with no separator between them.
var remarksLeadingTotalPattern = regexp.MustCompile(`^[\d,]+\.\d{2}`)

// productTableMarker is the last column header of the product table.
// Everything after it on the page is product rows plus the signature
// block — see productPattern.
const productTableMarker = "(Tiêu chuẩn ngoại quan)"

// productPattern reads one product row: barcode, PLU, carton count, unit
// of measure, loose-unit count, description and pack size, in the order
// the generator emits them.
//
// Every separator is \s* or \s+ rather than a newline, for the reason
// given in this file's own package comment: two of the four real samples
// have no newline in this row at all.
//
// The two quantity values are NOT interchangeable and the distinction is
// the whole point of this pattern: the first ("900.00") counts CARTONS,
// the second ("10,800.00") counts individual units, and it is the second
// one that goes into the order. Their relationship (cartons × pack size
// = units) is verified by the caller — see the processor's own
// consistency check — which is what makes a silent misalignment of this
// pattern detectable instead of becoming a wrong number in the
// accounting workbook.
var productPattern = regexp.MustCompile(`(?s)(\d{13})(\d+)\s+([\d,]+\.\d{2})\s*(\S+?)\s+([\d,]+\.\d{2})\s*(.*?)\s+([\d,]+\.\d{2})`)

// Branch is one of the two Maxidi legal entities that issue these
// delivery notes. They share a customer code in the MaKH sheet but bill
// under different names, tax codes and addresses, so an order has to
// carry its issuing branch's own invoicing details into columns H/I/J of
// the order workbook.
type Branch struct {
	TaxCode        string
	CustomerName   string
	InvoiceAddress string
}

// branchesByTaxCode maps the tax code printed on a delivery note to that
// branch's invoicing details, exactly as supplied by the project owner.
//
// The customer names and invoice addresses here are DELIBERATELY not
// read off the page. The letterhead prints the branch name in a slightly
// different form than accounting uses ("CHI NHÁNH ĐỒNG NAI-CÔNG TY..."
// with no spaces around the dash), and the letterhead address is the
// warehouse address, which for the Đồng Nai branch is not the address it
// invoices from. The tax code is the only field taken from the page,
// because it is the only one that identifies WHICH branch issued the
// note.
var branchesByTaxCode = map[string]Branch{
	"0317899481-002": {
		TaxCode:        "0317899481-002",
		CustomerName:   "CHI NHÁNH BÌNH DƯƠNG - CÔNG TY TNHH MAXIDI VIỆT NAM",
		InvoiceAddress: "Khu A, Kho Liên Anh, số 189/8 Lê Hồng Phong, KP Tân Phước, P.Tân Đông Hiệp, Hồ Chí Minh, Bình Dương",
	},
	"0317899481-001": {
		TaxCode:        "0317899481-001",
		CustomerName:   "CHI NHÁNH ĐỒNG NAI - CÔNG TY TNHH MAXIDI VIỆT NAM",
		InvoiceAddress: "Kho số 12, khuôn viên ICD Tân Cảng Long Bình, Phường Long Bình, Tỉnh Đồng Nai, Việt Nam.",
	},
}

// BranchForTaxCode looks up a branch's invoicing details. Returns
// ok=false for a tax code this project has never been given details for
// — a third Maxidi branch, or a page whose tax code was misread — so the
// caller can fail the page loudly instead of writing an order billed to
// nobody.
func BranchForTaxCode(taxCode string) (Branch, bool) {
	b, ok := branchesByTaxCode[strings.TrimSpace(taxCode)]
	return b, ok
}

// OrderInfo is everything this vendor's page header carries about the
// order itself, as printed — no defaults, no substitutions.
type OrderInfo struct {
	PONumber        string
	EntryDate       string
	ShipDate        string
	DeliveryAddress string
	Remarks         string
	TaxCode         string
}

// ParseOrderInfo extracts the page header. Returns ok=false unless EVERY
// field was found: a Maxidi delivery note that is missing its PO number,
// either date, the delivery address or the issuing branch's tax code is
// not a page this parser understood, and half-understood is the one
// outcome that must never reach the accounting workbook.
//
// Remarks is the single exception — it is genuinely optional on the
// template (the caption prints whether or not a note was entered), so an
// empty Remarks is a real, valid page rather than a parse failure.
func ParseOrderInfo(text string) (OrderInfo, bool) {
	taxMatch := taxCodePattern.FindStringSubmatch(text)
	orderMatch := entryDateAndPOPattern.FindStringSubmatch(text)
	shipMatch := shipDateAndAddressPattern.FindStringSubmatch(text)
	if taxMatch == nil || orderMatch == nil || shipMatch == nil {
		return OrderInfo{}, false
	}

	info := OrderInfo{
		TaxCode:         strings.TrimSpace(taxMatch[1]),
		EntryDate:       orderMatch[1],
		PONumber:        strings.TrimSpace(orderMatch[2]),
		ShipDate:        shipMatch[1],
		DeliveryAddress: strings.TrimSpace(shipMatch[2]),
	}
	if info.PONumber == "" || info.DeliveryAddress == "" || info.TaxCode == "" {
		return OrderInfo{}, false
	}

	if m := remarksPattern.FindStringSubmatch(text); m != nil {
		remarks := strings.TrimSpace(m[1])
		remarks = remarksLeadingTotalPattern.ReplaceAllString(remarks, "")
		info.Remarks = strings.TrimSpace(remarks)
	}
	return info, true
}

// Product is one line of the delivery note's product table.
//
// Qty is the LOOSE-UNIT count ("Số lượng lẻ", e.g. "10,800.00") — the
// quantity that goes into the order — while Cartons is the carton count
// the page leads with ("900.00"). Both are kept, unparsed and exactly as
// printed, so the caller can cross-check them against PackSize before
// trusting either.
//
// Name is captured but not used downstream: product names in the order
// workbook always come from the SanPham sheet, so that one name is used
// everywhere regardless of how each retailer spells it. It is kept here
// because it costs nothing and makes a misaligned parse obvious at a
// glance in a test failure.
type Product struct {
	Barcode  string
	PLU      string
	Cartons  string
	UoM      string
	Qty      string
	Name     string
	PackSize string
}

// ExtractProducts reads every product row on the page. Returns nil if
// the product table's own last column header is absent — a page that
// isn't a Maxidi delivery note, or one whose text extraction failed.
//
// Scans the region AFTER that header rather than matching one row at a
// fixed position: every real sample available carries exactly one
// product, and the project owner confirmed that is currently always the
// case, but a multi-row note must extract as several products rather
// than silently dropping every row but the first.
func ExtractProducts(text string) []Product {
	idx := strings.Index(text, productTableMarker)
	if idx < 0 {
		return nil
	}
	table := text[idx+len(productTableMarker):]

	var products []Product
	for _, m := range productPattern.FindAllStringSubmatch(table, -1) {
		products = append(products, Product{
			Barcode:  m[1],
			PLU:      m[2],
			Cartons:  m[3],
			UoM:      strings.TrimSpace(m[4]),
			Qty:      m[5],
			Name:     strings.TrimSpace(m[6]),
			PackSize: m[7],
		})
	}
	return products
}
