package processing

import (
	"bytes"
	"fmt"
	"regexp"
	"strconv"
)

// objectHeaderPattern matches a PDF indirect-object header ("11 0 obj")
// that starts its own line. Requiring a line start is what keeps this
// scan from matching the same three tokens appearing by coincidence
// inside a content or image stream's binary payload: every PDF
// generator writes real object headers at the start of a line, and a
// false positive here would put a bogus offset in the rebuilt table.
var objectHeaderPattern = regexp.MustCompile(`(?m)^[ \t]*(\d+)[ \t\r\n]+(\d+)[ \t\r\n]+obj\b`)

// trailerRootPattern pulls the catalog reference out of an existing
// trailer dictionary ("/Root 2 0 R").
var trailerRootPattern = regexp.MustCompile(`/Root[ \t\r\n]+(\d+)[ \t\r\n]+(\d+)[ \t\r\n]+R`)

// catalogObjectPattern finds the object that declares itself the
// document catalog, used only when no usable trailer survives.
var catalogObjectPattern = regexp.MustCompile(`(?m)^[ \t]*(\d+)[ \t\r\n]+(\d+)[ \t\r\n]+obj\b[\s\S]{0,400}?/Type[ \t\r\n]*/Catalog`)

// rebuildXref returns a copy of data with a freshly built
// cross-reference table, trailer and startxref appended, for a PDF whose
// existing table cannot be trusted.
//
// The confirmed real case (coop/testdata/realpdfs/103229379-00.pdf, PO
// 103229379) has a table whose every entry is wrong by a different
// amount — object N's recorded offset is exactly N+1 bytes past where
// that object actually starts — on top of a startxref that points at the
// file's own length instead of the table. Seeking to those offsets lands
// mid-header and the vendored library panics with `unexpected keyword
// "obj" parsing object`, so simply correcting startxref is not enough
// for this file: the table itself has to be discarded and rebuilt by
// scanning the objects, which is what every lenient real-world PDF
// reader does for a damaged table.
//
// Nothing already in the file moves — the rebuilt table is appended, so
// the offsets it records stay valid — and the library reads the LAST
// startxref within the file's final bytes, so the appended trailer is
// the one that wins. Returns ok=false when no objects can be found or no
// catalog can be identified, and refuses encrypted files outright rather
// than emitting a trailer that drops their /Encrypt entry.
func rebuildXref(data []byte) ([]byte, bool) {
	if bytes.Contains(data, []byte("/Encrypt")) {
		return nil, false
	}
	// A file this damaged frequently has unfinished stream lengths too —
	// see repairStreamLengths. Those corrections are appended as ordinary
	// objects first so the table built below indexes them, not the
	// originals they supersede.
	data = repairStreamLengths(data)
	offsets := scanObjectOffsets(data)
	if len(offsets) == 0 {
		return nil, false
	}
	root, ok := findCatalogRef(data)
	if !ok {
		return nil, false
	}

	maxObj := 0
	for num := range offsets {
		if num > maxObj {
			maxObj = num
		}
	}
	size := maxObj + 1

	var table bytes.Buffer
	fmt.Fprintf(&table, "xref\r\n0 %d\r\n", size)
	table.WriteString("0000000000 65535 f\r\n")
	for num := 1; num < size; num++ {
		offset, present := offsets[num]
		if !present {
			// A number no object claims must still occupy its slot, as a
			// free entry, so every later object stays on its own row.
			table.WriteString("0000000000 65535 f\r\n")
			continue
		}
		fmt.Fprintf(&table, "%010d 00000 n\r\n", offset)
	}

	repaired := make([]byte, 0, len(data)+table.Len()+96)
	repaired = append(repaired, data...)
	if len(repaired) > 0 && repaired[len(repaired)-1] != '\n' {
		repaired = append(repaired, '\r', '\n')
	}
	xrefOffset := len(repaired)
	repaired = append(repaired, table.Bytes()...)
	repaired = append(repaired, []byte(fmt.Sprintf("trailer\r\n<< /Size %d /Root %d %d R >>\r\nstartxref\r\n%d\r\n%%%%EOF\r\n",
		size, root.number, root.generation, xrefOffset))...)
	return repaired, true
}

// lengthRefWindow bounds how far back from a "stream" keyword
// repairStreamLengths looks for the /Length entry of the dictionary that
// introduces it — a stream dictionary is small, and a wider window would
// start finding the previous object's keys.
const lengthRefWindow = 400

// repairStreamLengths returns data with corrected /Length objects
// appended for every stream whose declared length is the placeholder 0
// while real bytes sit between "stream" and "endstream".
//
// The real Coop file this exists for (103229379-00.pdf, generated by
// "Txt2PDF-NTVan"/MIPDF per its own /Producer) writes each content
// stream as "<< /Length 9 0 R >> stream ... endstream" and then emits
// "9 0 obj 0 endobj" — the generator never went back to patch the
// length in. A reader that trusts it reads zero bytes and the page
// extracts as an empty string, which is why this file produced a
// "không nhận diện được nhà cung cấp" row even once its cross-reference
// table was rebuilt. Measuring the distance to "endstream" is what
// PyMuPDF (the reader the Python system used on this same file) does.
//
// Corrections are APPENDED as fresh definitions of the same object
// numbers rather than written over the originals: every offset already
// recorded elsewhere in the file stays valid, and scanObjectOffsets
// keeps the last definition of an object number, exactly as an
// incremental update behaves.
//
// Deliberately narrow: only a declared length of exactly 0 is treated as
// corrupt. A nonzero-but-wrong length is not repaired here, because
// "distance to the next endstream" is itself a heuristic — a binary
// stream may legitimately contain those bytes — and it should not be
// allowed to overrule a length the file states plainly.
func repairStreamLengths(data []byte) []byte {
	offsets := scanObjectOffsets(data)
	var appended bytes.Buffer
	for pos := 0; ; {
		idx := findPDFKeyword(data, pos, "stream")
		if idx < 0 {
			break
		}
		pos = idx + len("stream")
		start := pos
		if start < len(data) && data[start] == '\r' {
			start++
		}
		if start < len(data) && data[start] == '\n' {
			start++
		}
		end := findPDFKeyword(data, start, "endstream")
		if end < 0 {
			continue
		}
		length := end - start
		// The EOL immediately before "endstream" belongs to the keyword,
		// not to the stream's data (PDF spec §7.3.8.1).
		if length > 0 && data[start+length-1] == '\n' {
			length--
		}
		if length > 0 && data[start+length-1] == '\r' {
			length--
		}
		if length <= 0 {
			continue
		}
		number, ok := lengthObjectBefore(data, idx)
		if !ok {
			continue
		}
		offset, present := offsets[number]
		if !present {
			continue
		}
		if declared, ok := indirectInteger(data, offset); !ok || declared != 0 {
			continue
		}
		fmt.Fprintf(&appended, "\r\n%d 0 obj\r\n%d\r\nendobj\r\n", number, length)
	}
	if appended.Len() == 0 {
		return data
	}
	patched := make([]byte, 0, len(data)+appended.Len())
	patched = append(patched, data...)
	return append(patched, appended.Bytes()...)
}

// lengthObjectBefore returns the object number of the "/Length N G R"
// entry in the stream dictionary that ends just before streamIdx.
func lengthObjectBefore(data []byte, streamIdx int) (int, bool) {
	from := streamIdx - lengthRefWindow
	if from < 0 {
		from = 0
	}
	rel := bytes.LastIndex(data[from:streamIdx], []byte("/Length"))
	if rel < 0 {
		return 0, false
	}
	rest := data[from+rel+len("/Length") : streamIdx]
	number, next, ok := parseOffsetAt(rest)
	if !ok {
		return 0, false
	}
	if _, afterGen, ok := parseOffsetAt(rest[next:]); ok {
		tail := bytes.TrimLeft(rest[next+afterGen:], " \t\r\n\f")
		if len(tail) > 0 && tail[0] == 'R' {
			return number, true
		}
	}
	return 0, false
}

// indirectInteger reads the integer body of the indirect object whose
// header starts at offset ("9 0 obj 0 endobj" -> 0).
func indirectInteger(data []byte, offset int) (int, bool) {
	if offset < 0 || offset >= len(data) {
		return 0, false
	}
	rest := data[offset:]
	_, next, ok := parseOffsetAt(rest)
	if !ok {
		return 0, false
	}
	_, afterGen, ok := parseOffsetAt(rest[next:])
	if !ok {
		return 0, false
	}
	rest = bytes.TrimLeft(rest[next+afterGen:], " \t\r\n\f")
	if !bytes.HasPrefix(rest, []byte("obj")) {
		return 0, false
	}
	value, _, ok := parseOffsetAt(rest[len("obj"):])
	return value, ok
}

type objectRef struct {
	number     int
	generation int
}

// scanObjectOffsets maps each object number to the byte offset of its
// header. A later definition wins, matching how an incrementally
// updated PDF supersedes an earlier version of the same object.
func scanObjectOffsets(data []byte) map[int]int {
	offsets := make(map[int]int)
	for _, m := range objectHeaderPattern.FindAllSubmatchIndex(data, -1) {
		num, err := strconv.Atoi(string(data[m[2]:m[3]]))
		if err != nil || num <= 0 {
			continue
		}
		// m[2] is the first digit of the object number, which is where
		// the object itself starts — not m[0], which may include the
		// leading indentation the pattern tolerates.
		offsets[num] = m[2]
	}
	return offsets
}

// findCatalogRef returns the document catalog's object reference, taken
// from the last trailer that names one, or failing that from the object
// that declares /Type /Catalog itself.
func findCatalogRef(data []byte) (objectRef, bool) {
	if matches := trailerRootPattern.FindAllSubmatch(data, -1); len(matches) > 0 {
		last := matches[len(matches)-1]
		number, errNum := strconv.Atoi(string(last[1]))
		generation, errGen := strconv.Atoi(string(last[2]))
		if errNum == nil && errGen == nil {
			return objectRef{number: number, generation: generation}, true
		}
	}
	if m := catalogObjectPattern.FindSubmatch(data); m != nil {
		number, errNum := strconv.Atoi(string(m[1]))
		generation, errGen := strconv.Atoi(string(m[2]))
		if errNum == nil && errGen == nil {
			return objectRef{number: number, generation: generation}, true
		}
	}
	return objectRef{}, false
}
